version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount source code for development
      - ./src:/app/src
      # Mount logs directory
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
    # Enable interactive terminal
    tty: true
    stdin_open: true
    # Restart policy for development
    restart: unless-stopped
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import os; assert os.getenv('TELEGRAM_BOT_TOKEN')"]
      interval: 30s
      timeout: 10s
      retries: 3