version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount the source code directory to enable hot-reloading
      - ./src:/app/src
      # Mount the .env file for configuration
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=development
    # Use the development command that includes auto-reloading
    command: python -m src.bot
    # Uncomment this if you want to use a debugger with Docker
    # ports:
    #   - "5678:5678"
    # command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m src.bot
    restart: unless-stopped